### ISSUE TITLE
Style Tags

### ISSUE THREAD

**Issue by aniehuser** [aniehuser/senior-design-group10#103]
Make a css class that styles tags to look nice

something like what is seen here: https://bulma.io/documentation/elements/tag/

**Comment by aniehuser** [comment]
or you could look into a css library and begin integrating that as well

**Comment by aniehuser** [comment]
> or you could look into a css library and begin integrating that as well

heres a list of popular css libraries http://cssdb.co/

**Comment by clundin55** [comment]
PR out now
