### ISSUE TITLE
investigate if we should be bolding both keys and values

### ISSUE THREAD

**Issue by aniehuser** [aniehuser/senior-design-group10#113]
See comment [here](https://github.com/aniehuser/senior-design-group10/pull/111/files/626b14652753ac72161f0681fe2764753f5d2f52#r270999284). We should investigate whether or not we want these bolded.

Definition of done:
if it's fine, leave as is and close this issue
else, bold or unbold the entire thing

**Comment by Brewer-Slack** [comment]
Has this issue been resolved?

**Comment by Brewer-Slack** [comment]
The branch has been merged. Closing this issue
