### ISSUE TITLE
CLI Executable

### ISSUE THREAD

**Issue by Brewer-Slack** [aniehuser/senior-design-group10#138]
Bowers still doesn't like how we have to run the cli using the` java -jar` keywords, we should look into solutions to making the jar into a clickable executable that will open up the CLI.

**Comment by aniehuser** [comment]
this is lower priority i think

**Comment by clundin55** [comment]
I say we close this, looked at this briefly we would have to create a .app for it to be an executable in MacOS and a .exe for windows, seems unnecessary
