### ISSUE TITLE
rest endpoint timezones

### ISSUE THREAD

**Issue by clundin55** [aniehuser/senior-design-group10#97]
We need to make sure the dates being added to our database entries are in the correct timezone

**Comment by aniehuser** [comment]
Note that dates sent from the Yesworkflow CLI in the list of objects in  `resources` field are sent in UTC format

**Comment by Brewer-Slack** [comment]
I will take this.

**Comment by Brewer-Slack** [comment]
https://github.com/aniehuser/senior-design-group10/pull/149
